export const GET_PLACE_DETAILS_START = 'GET_PLACE_DETAILS_START';
export const GET_PLACE_DETAILS_FAILURE = 'GET_PLACE_DETAILS_FAILURE';
export const GET_PLACE_DETAILS_SUCCESS = 'GET_PLACE_DETAILS_SUCCESS';
export const GET_SELECTED_PLACE_DETAILS_START = 'GET_SELECTED_PLACE_DETAILS_START';
export const GET_SELECTED_PLACE_DETAILS_FAILURE = 'GET_SELECTED_PLACE_DETAILS_FAILURE';
export const GET_SELECTED_PLACE_DETAILS_SUCCESS = 'GET_SELECTED_PLACE_DETAILS_SUCCESS';